### ISSUE TITLE
ConvertTo-Yaml does not supply quotes in YAML files for strings

### ISSUE THREAD

**Issue by ChristopherGLewis** [cloudbase/powershell-yaml#38]
Conversion of strings is missing quote characters and can result in dropped characters with IP address fragments.
```
PS C:\VSProjects\ansible> get-module Powershell-yaml

ModuleType Version    Name                                ExportedCommands                                                                             
---------- -------    ----                                ----------------                                                                             
Script     0.3.7      powershell-yaml                     {ConvertFrom-Yaml, ConvertTo-Yaml, cfy, cty}                                                 

```
I store IP addresses in two fields
```
PS C:\> $A = @{ IProot="10.100"; IPTail = "0.100" }

PS C:\> $A

Name                           Value                                                                                                                   
----                           -----                                                                                                                   
IProot                         10.100                                                                                                                  
IPTail                         0.100                                                                                                                   



PS C:\> $A | ConvertTo-Yaml
IProot: 10.100
IPTail: 0.100


PS C:\> $A | ConvertTo-Yaml | ConvertFrom-Yaml

Name                           Value                                                                                                                   
----                           -----                                                                                                                   
IProot                         10.1                                                                                                                    
IPTail                         0.1   

```
Expected result is for these values to NOT drop trailing zeros.

**Comment by gabriel-samfira** [comment]
Both this and the previous bug should be fixable if YamlDotNet would use quotes for strings that could be cast to something other than strings.

The problem is that YamlDotNet uses ```Plain``` scalar types for strings. This creates a problem when passing in integers/floats as strings. Type gets lost. See:

https://github.com/aaubry/YamlDotNet/issues/33#issuecomment-449397619

I will create a branch after the holidays which includes a modified version of YamlDotNet, which you can take for a spin. Would that be acceptable?

**Comment by chrisvanderpennen** [comment]
...well I was going to say I've been working on a fix for this and #37, but apparently github beat me to it.  Would you like a pull request?

**Comment by gabriel-samfira** [comment]
If you already did the work, feel free to propose a PR, and we can discuss it.

**Comment by gabriel-samfira** [comment]
Fixed by: https://github.com/cloudbase/powershell-yaml/pull/41

Let us know if you see any issues with the master branch.

**Comment by Ash258** [comment]
I am still facing this issue on master (from today; 4f54411)

```powershell
"version: '1.5.6'" | ConvertFrom-Yaml | ConvertTo-Yaml
```

![Now](https://i.imgur.com/57GAMZc.png)

Powershell 5.1.17134.407; pwsh 6.1.2

**Comment by Ash258** [comment]
But simple value works: 

![Strange](https://i.imgur.com/rSOysuw.png)
